spring:
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:3306/wechat_fms?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: xxxx
    password: xxxx
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.bupt.service.bean
